# Generated by Django 4.2.3 on 2023-07-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('explain', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
