# Generated by Django 4.2.3 on 2023-07-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reborn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='img',
            field=models.ImageField(upload_to='partner/'),
        ),
    ]
